cmake_minimum_required(VERSION 3.22.1)
project(kraken_npu LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(RUNTIME_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../jniLibs/${ANDROID_ABI})
foreach(name llama ggml ggml-base ggml-cpu ggml-opencl ggml-hexagon)
  add_library(${name} SHARED IMPORTED)
  set_target_properties(${name} PROPERTIES IMPORTED_LOCATION ${RUNTIME_DIR}/lib${name}.so)
endforeach()
add_library(kraken_npu SHARED kraken_npu.cpp)
target_include_directories(kraken_npu PRIVATE include)
target_link_libraries(kraken_npu llama ggml ggml-base log)
target_link_options(kraken_npu PRIVATE "-Wl,-z,max-page-size=16384")
