// Relevant defaults transcribed from v0.20.19 idl/llm_options.proto.
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_MAX_OUTPUT_TOKENS 512
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_TEMPERATURE 0.7f
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_TOP_P 1.0f
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_TOP_K 40
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_REPEAT_PENALTY 1.1f
