import 'dart:convert';
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:archive/archive.dart';
import 'package:kraken_hub/spokes/meeting_notes/data/folder_repository.dart';

/// Centralized export service for meeting recordings.
///
/// Generates professional-grade documents from recording data:
/// - **PDF**: Formatted multi-page document with cover, summary, transcript
/// - **DOCX**: Word document with built-in heading styles, fully editable
/// - **TXT**: Plain text transcript
///
/// All exports are written to the system temp directory and cleaned up
/// on the next export operation or app launch.
class KrakenExportService {
  KrakenExportService();

  // ─── Temp Cleanup ───────────────────────────────────────────────────────────

  /// Remove stale export files from the temp directory.
  static Future<void> cleanupTempExports() async {
    try {
      final dir = await getTemporaryDirectory();
      final exports = dir.listSync().whereType<File>().where((f) {
        final name = f.uri.pathSegments.last;
        return name.startsWith('kraken_') &&
            (name.endsWith('.pdf') ||
                name.endsWith('.docx') ||
                name.endsWith('.txt') ||
                name.endsWith('.md'));
      });
      for (final file in exports) {
        try {
          await file.delete();
        } catch (_) {}
      }
    } catch (_) {}
  }

  static String safeFileName(String title) {
    // Strip common audio file extensions from title
    String clean = title;
    for (final ext in ['.mp3', '.m4a', '.wav', '.aac', '.ogg', '.flac', '.wma']) {
      if (clean.toLowerCase().endsWith(ext)) {
        clean = clean.substring(0, clean.length - ext.length);
      }
    }
    return clean.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(RegExp(r'\s+'), '_');
  }

  // ─── Text Chunking ─────────────────────────────────────────────────────────

  /// Split a long text into chunks that fit on a single PDF page.
  /// Breaks at word boundaries to avoid cutting words.
  static List<String> _chunkText(String text, {int maxChars = 500}) {
    if (text.length <= maxChars) return [text];

    final chunks = <String>[];

    // First split on newlines
    final lines = text.split('\n');
    final buffer = StringBuffer();

    for (final line in lines) {
      if (line.trim().isEmpty) continue;

      // If a single line exceeds maxChars, split it at word boundaries
      if (line.length > maxChars) {
        // Flush buffer first
        if (buffer.isNotEmpty) {
          chunks.add(buffer.toString().trim());
          buffer.clear();
        }

        final words = line.split(' ');
        final wordBuf = StringBuffer();
        for (final word in words) {
          if (wordBuf.length + word.length + 1 > maxChars && wordBuf.isNotEmpty) {
            chunks.add(wordBuf.toString().trim());
            wordBuf.clear();
          }
          if (wordBuf.isNotEmpty) wordBuf.write(' ');
          wordBuf.write(word);
        }
        if (wordBuf.isNotEmpty) {
          buffer.write(wordBuf.toString());
        }
      } else if (buffer.length + line.length + 1 > maxChars) {
        chunks.add(buffer.toString().trim());
        buffer.clear();
        buffer.writeln(line);
      } else {
        if (buffer.isNotEmpty) buffer.write(' ');
        buffer.write(line);
      }
    }

    if (buffer.isNotEmpty) {
      chunks.add(buffer.toString().trim());
    }

    // Safety: if we somehow still have empty list, return original text in chunks
    if (chunks.isEmpty) {
      for (int i = 0; i < text.length; i += maxChars) {
        final end = (i + maxChars > text.length) ? text.length : i + maxChars;
        chunks.add(text.substring(i, end));
      }
    }

    return chunks.where((c) => c.isNotEmpty).toList();
  }

  // ─── PDF Export ─────────────────────────────────────────────────────────────

  /// Generate a professional PDF document from a recording.
  ///
  /// Layout:
  /// - Cover area: title, date, duration
  /// - Executive summary (if available)
  /// - Key points, decisions, action items
  /// - Full transcript with timestamps
  /// - Footer: page numbers + "Generated by The Kraken"
  Future<File> exportPdf({
    required Recording recording,
    required String title,
    String? transcriptText,
    String? summaryJson,
  }) async {

    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: pw.Font.helvetica(),
        bold: pw.Font.helveticaBold(),
        italic: pw.Font.helveticaOblique(),
        boldItalic: pw.Font.helveticaBoldOblique(),
      ),
    );

    // Parse summary JSON
    Map<String, dynamic>? summary;
    if (summaryJson != null && summaryJson.isNotEmpty) {
      try {
        String raw = summaryJson.trim();
        if (raw.startsWith('```')) {
          final lines = raw.split('\n');
          if (lines.length > 2) raw = lines.sublist(1, lines.length - 1).join('\n');
        }
        summary = jsonDecode(raw) as Map<String, dynamic>;
      } catch (_) {}
    }

    final dateStr = _formatDate(recording.meetingDate);
    final durationStr = _formatDuration(recording.durationMs);

    // ── Build pages ──
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(48),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          // Cover area
          _buildCover(title, dateStr, durationStr),
          pw.SizedBox(height: 24),

          // Summary sections
          if (summary != null) ...[
            if (summary['tldr'] != null) ...[
              _sectionHeader('Summary'),
              _bodyText(summary['tldr'] as String),
              pw.SizedBox(height: 16),
            ],
            if (summary['summary'] != null) ...[
              _sectionHeader('Executive Summary'),
              _bodyText(summary['summary'] as String),
              pw.SizedBox(height: 16),
            ],
            ..._buildListItems('Key Points', summary['key_points']),
            ..._buildListItems('Decisions', summary['decisions']),
            ..._buildChecklistItems('Action Items', summary['action_items']),
            ..._buildListItems('Open Questions', summary['open_questions']),
          ],

          // Transcript — chunked into page-safe paragraphs
          if (transcriptText != null && transcriptText.isNotEmpty) ...[
            pw.Divider(color: PdfColors.grey400),
            pw.SizedBox(height: 12),
            _sectionHeader('Full Transcript'),
            pw.SizedBox(height: 8),
            ..._chunkText(transcriptText).map(
              (chunk) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 6),
                child: _bodyText(chunk),
              ),
            ),
          ],
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/kraken_${safeFileName(title)}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  // ── PDF building blocks ──

  pw.Widget _buildCover(String title, String date, String duration) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(24),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#1A1B2E'),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              font: pw.Font.helveticaBold(),
              fontSize: 22,
              color: PdfColors.white,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Row(children: [
            pw.Text(
              date,
              style: pw.TextStyle(fontSize: 12, color: PdfColor.fromHex('#A5B4FC')),
            ),
            pw.SizedBox(width: 16),
            pw.Text(
              duration,
              style: pw.TextStyle(fontSize: 12, color: PdfColor.fromHex('#A5B4FC')),
            ),
          ]),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(pw.Context context) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'Generated by The Kraken',
          style: pw.TextStyle(
            fontSize: 9,
            color: PdfColors.grey500,
            fontItalic: pw.Font.helveticaOblique(),
          ),
        ),
        pw.Text(
          'Page ${context.pageNumber} of ${context.pagesCount}',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
        ),
      ],
    );
  }

  pw.Widget _sectionHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          font: pw.Font.helveticaBold(),
          fontSize: 14,
          color: PdfColor.fromHex('#818CF8'),
        ),
      ),
    );
  }

  pw.Widget _bodyText(String text) {
    return pw.Text(
      text,
      style: const pw.TextStyle(fontSize: 11, lineSpacing: 4),
    );
  }

  /// Build list section items as flat widgets (not wrapped in Column)
  /// so MultiPage can break them across pages.
  List<pw.Widget> _buildListItems(String heading, dynamic items) {
    if (items == null || items is! List || items.isEmpty) return [];
    return [
      _sectionHeader(heading),
      ...items.map<pw.Widget>((item) => pw.Padding(
            padding: const pw.EdgeInsets.only(left: 12, bottom: 3),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('-  ', style: pw.TextStyle(font: pw.Font.helveticaBold(), fontSize: 11)),
                pw.Expanded(child: _bodyText(item.toString())),
              ],
            ),
          )),
      pw.SizedBox(height: 16),
    ];
  }

  List<pw.Widget> _buildChecklistItems(String heading, dynamic items) {
    if (items == null || items is! List || items.isEmpty) return [];
    return [
      _sectionHeader(heading),
      ...items.map<pw.Widget>((item) => pw.Padding(
            padding: const pw.EdgeInsets.only(left: 12, bottom: 3),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  width: 10, height: 10,
                  margin: const pw.EdgeInsets.only(top: 2, right: 6),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey600, width: 1),
                    borderRadius: pw.BorderRadius.circular(2),
                  ),
                ),
                pw.Expanded(child: _bodyText(item.toString())),
              ],
            ),
          )),
      pw.SizedBox(height: 16),
    ];
  }

  // ─── DOCX Export ────────────────────────────────────────────────────────────

  /// Generate a Word (.docx) document from a recording.
  ///
  /// Word documents are ZIP archives containing XML. This builds the
  /// complete OOXML structure with proper heading styles and required parts.
  Future<File> exportDocx({
    required Recording recording,
    required String title,
    String? transcriptText,
    String? summaryJson,
  }) async {

    // Parse summary
    Map<String, dynamic>? summary;
    if (summaryJson != null && summaryJson.isNotEmpty) {
      try {
        String raw = summaryJson.trim();
        if (raw.startsWith('```')) {
          final lines = raw.split('\n');
          if (lines.length > 2) raw = lines.sublist(1, lines.length - 1).join('\n');
        }
        summary = jsonDecode(raw) as Map<String, dynamic>;
      } catch (_) {}
    }

    final dateStr = _formatDate(recording.meetingDate);
    final durationStr = _formatDuration(recording.durationMs);

    // Build document.xml content
    final body = StringBuffer();
    body.writeln('<w:body>');

    // Title
    body.writeln(_docxParagraph(title, style: 'Title'));
    body.writeln(_docxParagraph('$dateStr  •  $durationStr', style: 'Subtitle'));
    body.writeln(_docxParagraph(''));

    // Summary
    if (summary != null) {
      if (summary['tldr'] != null) {
        body.writeln(_docxParagraph('Summary', style: 'Heading1'));
        body.writeln(_docxParagraph(summary['tldr'] as String));
        body.writeln(_docxParagraph(''));
      }
      if (summary['summary'] != null) {
        body.writeln(_docxParagraph('Executive Summary', style: 'Heading1'));
        body.writeln(_docxParagraph(summary['summary'] as String));
        body.writeln(_docxParagraph(''));
      }
      _docxListSection(body, 'Key Points', summary['key_points']);
      _docxListSection(body, 'Decisions', summary['decisions']);
      _docxListSection(body, 'Action Items', summary['action_items']);
      _docxListSection(body, 'Open Questions', summary['open_questions']);
    }

    // Transcript
    if (transcriptText != null && transcriptText.isNotEmpty) {
      body.writeln(_docxParagraph('Full Transcript', style: 'Heading1'));
      // Split transcript into manageable paragraphs
      final chunks = _chunkText(transcriptText, maxChars: 2000);
      for (final chunk in chunks) {
        body.writeln(_docxParagraph(chunk));
      }
    }

    // Footer
    body.writeln(_docxParagraph(''));
    body.writeln(_docxParagraph('Generated by The Kraken', italic: true, color: '808080'));

    // Section properties (required for valid DOCX)
    body.writeln('<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/></w:sectPr>');
    body.writeln('</w:body>');

    // Assemble OOXML ZIP
    final archive = Archive();

    // Helper to add a properly sized file
    void addXml(String path, String content) {
      final bytes = utf8.encode(content);
      archive.addFile(ArchiveFile(path, bytes.length, bytes));
    }

    addXml('[Content_Types].xml', _contentTypesXml);
    addXml('_rels/.rels', _relsXml);
    addXml('word/_rels/document.xml.rels', _docRelsXml);
    addXml('word/styles.xml', _stylesXml);
    addXml('word/settings.xml', _settingsXml);
    addXml('word/fontTable.xml', _fontTableXml);

    // word/document.xml — minimal namespace declarations
    final documentXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
${body.toString()}
</w:document>''';

    addXml('word/document.xml', documentXml);

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/kraken_${safeFileName(title)}.docx');
    final encoded = ZipEncoder().encode(archive);
    if (encoded != null) {
      await file.writeAsBytes(encoded);
    }
    return file;
  }

  // ── DOCX XML helpers ──

  String _docxParagraph(String text, {String? style, bool italic = false, String? color}) {
    final escaped = _xmlEscape(text);
    final stylePart = style != null
        ? '<w:pPr><w:pStyle w:val="$style"/></w:pPr>'
        : '';
    final runProps = StringBuffer();
    if (italic) runProps.write('<w:i/>');
    if (color != null) runProps.write('<w:color w:val="$color"/>');
    final rPr = runProps.isNotEmpty ? '<w:rPr>${runProps.toString()}</w:rPr>' : '';

    return '<w:p>$stylePart<w:r>$rPr<w:t xml:space="preserve">$escaped</w:t></w:r></w:p>';
  }

  void _docxListSection(StringBuffer body, String heading, dynamic items) {
    if (items == null || items is! List || items.isEmpty) return;
    body.writeln(_docxParagraph(heading, style: 'Heading2'));
    for (final item in items) {
      body.writeln(_docxParagraph('-  ${item.toString()}'));
    }
    body.writeln(_docxParagraph(''));
  }

  String _xmlEscape(String text) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }

  // ── OOXML boilerplate ──

  static const _contentTypesXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>
  <Override PartName="/word/fontTable.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"/>
</Types>''';

  static const _relsXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>''';

  static const _docRelsXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/>
</Relationships>''';

  static const _settingsXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
  xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:zoom w:percent="100"/>
  <w:defaultTabStop w:val="720"/>
  <w:characterSpacingControl w:val="doNotCompress"/>
  <w:compat>
    <w:compatSetting w:name="compatibilityMode" w:uri="http://schemas.microsoft.com/office/word" w:val="15"/>
  </w:compat>
</w:settings>''';

  static const _fontTableXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:fonts xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:font w:name="Calibri">
    <w:panose1 w:val="020F0502020204030204"/>
    <w:charset w:val="00"/>
    <w:family w:val="swiss"/>
    <w:pitch w:val="variable"/>
  </w:font>
  <w:font w:name="Times New Roman">
    <w:panose1 w:val="02020603050405020304"/>
    <w:charset w:val="00"/>
    <w:family w:val="roman"/>
    <w:pitch w:val="variable"/>
  </w:font>
</w:fonts>''';

  static const _stylesXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:docDefaults>
    <w:rPrDefault>
      <w:rPr>
        <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:eastAsia="Calibri" w:cs="Calibri"/>
        <w:sz w:val="22"/>
        <w:szCs w:val="22"/>
        <w:lang w:val="en-US"/>
      </w:rPr>
    </w:rPrDefault>
    <w:pPrDefault>
      <w:pPr>
        <w:spacing w:after="160" w:line="259" w:lineRule="auto"/>
      </w:pPr>
    </w:pPrDefault>
  </w:docDefaults>
  <w:style w:type="paragraph" w:styleId="Normal" w:default="1">
    <w:name w:val="Normal"/>
    <w:qFormat/>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Title">
    <w:name w:val="Title"/>
    <w:basedOn w:val="Normal"/>
    <w:qFormat/>
    <w:pPr><w:spacing w:after="120" w:line="240" w:lineRule="auto"/></w:pPr>
    <w:rPr><w:b/><w:sz w:val="56"/><w:szCs w:val="56"/><w:color w:val="1A1B2E"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Subtitle">
    <w:name w:val="Subtitle"/>
    <w:basedOn w:val="Normal"/>
    <w:qFormat/>
    <w:pPr><w:spacing w:after="360"/></w:pPr>
    <w:rPr><w:sz w:val="24"/><w:szCs w:val="24"/><w:color w:val="818CF8"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading1">
    <w:name w:val="heading 1"/>
    <w:basedOn w:val="Normal"/>
    <w:qFormat/>
    <w:pPr><w:keepNext/><w:keepLines/><w:spacing w:before="360" w:after="120"/><w:outlineLvl w:val="0"/></w:pPr>
    <w:rPr><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/><w:color w:val="818CF8"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading2">
    <w:name w:val="heading 2"/>
    <w:basedOn w:val="Normal"/>
    <w:qFormat/>
    <w:pPr><w:keepNext/><w:keepLines/><w:spacing w:before="240" w:after="80"/><w:outlineLvl w:val="1"/></w:pPr>
    <w:rPr><w:b/><w:sz w:val="26"/><w:szCs w:val="26"/><w:color w:val="333333"/></w:rPr>
  </w:style>
</w:styles>''';

  // ─── Shared helpers ─────────────────────────────────────────────────────────

  String _formatDate(DateTime dt) {
    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return '${months[dt.month - 1]} ${dt.day}, ${dt.year}';
  }

  String _formatDuration(int ms) {
    final d = Duration(milliseconds: ms);
    final mins = d.inMinutes;
    final secs = d.inSeconds % 60;
    if (mins == 0) return '${secs}s';
    return '${mins}m ${secs}s';
  }
}
